# Security Workflow - Assistente de Regulação Médica
# 
# Workflow automático para verificações de segurança
# Executa dependency scanning, code analysis e validações específicas para extensões

name: 🔒 Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Executa toda segunda-feira às 9:00 UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
    inputs:
      deep_scan:
        description: 'Enable deep security scan'
        required: false
        default: false
        type: boolean

# Configurações globais
env:
  NODE_VERSION: '18.x'

# Permissões necessárias
permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  # === JOB 1: DEPENDENCY SCANNING ===
  dependency-scan:
    name: 📦 Dependency Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4
      
      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: 📦 Install Dependencies
        run: |
          npm ci --prefer-offline --no-audit
          echo "✅ Dependencies installed"
      
      - name: 🔒 Run npm audit
        run: |
          echo "🔍 Running npm audit..."
          npm audit --audit-level=moderate --json > audit-results.json || true
          
          # Processa resultados
          VULNERABILITIES=$(cat audit-results.json | jq -r '.metadata.vulnerabilities | to_entries[] | "\(.key): \(.value)"' 2>/dev/null || echo "No vulnerabilities data")
          
          echo "### 📦 Dependency Audit Results" >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
          echo "$VULNERABILITIES" >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
          
          # Verifica se há vulnerabilidades críticas
          CRITICAL=$(cat audit-results.json | jq -r '.metadata.vulnerabilities.critical // 0' 2>/dev/null || echo "0")
          HIGH=$(cat audit-results.json | jq -r '.metadata.vulnerabilities.high // 0' 2>/dev/null || echo "0")
          
          if [[ "$CRITICAL" -gt 0 || "$HIGH" -gt 0 ]]; then
            echo "❌ Critical or high vulnerabilities found!"
            echo "Critical: $CRITICAL, High: $HIGH"
            exit 1
          else
            echo "✅ No critical or high vulnerabilities found"
          fi
      
      - name: 📋 Upload Audit Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependency-audit-results
          path: audit-results.json
          retention-days: 30

  # === JOB 2: CODE SECURITY ANALYSIS ===
  code-analysis:
    name: 🔍 Code Security Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4
      
      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: 📦 Install Dependencies
        run: npm ci --prefer-offline --no-audit
      
      - name: 🔒 Run Security Validation
        run: |
          echo "🔍 Running security validation..."
          npm run validate -- --skip-linting
          echo "✅ Security validation completed"
      
      - name: 🔍 Manual Security Checks
        run: |
          echo "🔍 Running manual security checks..."
          
          # Busca por padrões inseguros
          echo "### 🔒 Security Pattern Analysis" >> $GITHUB_STEP_SUMMARY
          
          # innerHTML usage
          INNERHTML_COUNT=$(grep -r "innerHTML" --include="*.js" . | wc -l || echo "0")
          echo "- **innerHTML usage**: $INNERHTML_COUNT occurrences" >> $GITHUB_STEP_SUMMARY
          
          # eval usage
          EVAL_COUNT=$(grep -r "eval(" --include="*.js" . | wc -l || echo "0")
          echo "- **eval() usage**: $EVAL_COUNT occurrences" >> $GITHUB_STEP_SUMMARY
          
          # document.write usage
          DOCWRITE_COUNT=$(grep -r "document.write" --include="*.js" . | wc -l || echo "0")
          echo "- **document.write usage**: $DOCWRITE_COUNT occurrences" >> $GITHUB_STEP_SUMMARY
          
          # javascript: URLs
          JSURL_COUNT=$(grep -r "javascript:" --include="*.js" . | wc -l || echo "0")
          echo "- **javascript: URLs**: $JSURL_COUNT occurrences" >> $GITHUB_STEP_SUMMARY
          
          # Direct chrome API usage
          CHROME_API_COUNT=$(grep -r "chrome\." --include="*.js" . | grep -v "globalThis.browser || globalThis.chrome" | wc -l || echo "0")
          echo "- **Direct chrome.* API usage**: $CHROME_API_COUNT occurrences" >> $GITHUB_STEP_SUMMARY
          
          # Verifica se há problemas críticos
          if [[ "$EVAL_COUNT" -gt 0 ]]; then
            echo "❌ eval() usage detected - forbidden in Manifest V3!"
            exit 1
          fi
          
          if [[ "$INNERHTML_COUNT" -gt 5 ]]; then
            echo "⚠️ High innerHTML usage detected - review for XSS vulnerabilities"
          fi
          
          echo "✅ Manual security checks completed"

  # === JOB 3: MANIFEST SECURITY VALIDATION ===
  manifest-security:
    name: 📄 Manifest Security Validation
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4
      
      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: 📦 Install Dependencies
        run: npm ci --prefer-offline --no-audit
      
      - name: 📄 Validate Manifests
        run: |
          echo "📄 Validating manifest security..."
          npm run validate:manifests
          echo "✅ Manifest validation completed"
      
      - name: 🔒 Manifest Security Analysis
        run: |
          echo "🔒 Analyzing manifest security..."
          
          echo "### 📄 Manifest Security Analysis" >> $GITHUB_STEP_SUMMARY
          
          # Analisa manifest.json (Firefox)
          if [[ -f "manifest.json" ]]; then
            echo "#### Firefox Manifest (manifest.json)" >> $GITHUB_STEP_SUMMARY
            
            # Verifica permissões
            PERMISSIONS=$(cat manifest.json | jq -r '.permissions[]?' 2>/dev/null || echo "")
            HOST_PERMISSIONS=$(cat manifest.json | jq -r '.host_permissions[]?' 2>/dev/null || echo "")
            
            echo "**Permissions:**" >> $GITHUB_STEP_SUMMARY
            if [[ -n "$PERMISSIONS" ]]; then
              echo "$PERMISSIONS" | while read -r perm; do
                if [[ -n "$perm" ]]; then
                  echo "- $perm" >> $GITHUB_STEP_SUMMARY
                fi
              done
            else
              echo "- None" >> $GITHUB_STEP_SUMMARY
            fi
            
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Host Permissions:**" >> $GITHUB_STEP_SUMMARY
            if [[ -n "$HOST_PERMISSIONS" ]]; then
              echo "$HOST_PERMISSIONS" | while read -r perm; do
                if [[ -n "$perm" ]]; then
                  echo "- $perm" >> $GITHUB_STEP_SUMMARY
                  
                  # Verifica permissões amplas
                  if [[ "$perm" == "*://*/*" || "$perm" == "<all_urls>" ]]; then
                    echo "⚠️ Broad host permission detected: $perm"
                  fi
                fi
              done
            else
              echo "- None" >> $GITHUB_STEP_SUMMARY
            fi
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Analisa manifest-edge.json (Chrome)
          if [[ -f "manifest-edge.json" ]]; then
            echo "#### Chrome Manifest (manifest-edge.json)" >> $GITHUB_STEP_SUMMARY
            
            # Verifica permissões
            PERMISSIONS=$(cat manifest-edge.json | jq -r '.permissions[]?' 2>/dev/null || echo "")
            HOST_PERMISSIONS=$(cat manifest-edge.json | jq -r '.host_permissions[]?' 2>/dev/null || echo "")
            
            echo "**Permissions:**" >> $GITHUB_STEP_SUMMARY
            if [[ -n "$PERMISSIONS" ]]; then
              echo "$PERMISSIONS" | while read -r perm; do
                if [[ -n "$perm" ]]; then
                  echo "- $perm" >> $GITHUB_STEP_SUMMARY
                fi
              done
            else
              echo "- None" >> $GITHUB_STEP_SUMMARY
            fi
            
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Host Permissions:**" >> $GITHUB_STEP_SUMMARY
            if [[ -n "$HOST_PERMISSIONS" ]]; then
              echo "$HOST_PERMISSIONS" | while read -r perm; do
                if [[ -n "$perm" ]]; then
                  echo "- $perm" >> $GITHUB_STEP_SUMMARY
                fi
              done
            else
              echo "- None" >> $GITHUB_STEP_SUMMARY
            fi
          fi
          
          echo "✅ Manifest security analysis completed"

  # === JOB 4: SECRETS SCANNING ===
  secrets-scan:
    name: 🔐 Secrets Scanning
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 🔐 Scan for Secrets
        run: |
          echo "🔐 Scanning for potential secrets..."
          
          # Padrões de secrets comuns
          declare -A patterns=(
            ["API Keys"]="[Aa][Pp][Ii][_-]?[Kk][Ee][Yy].*['\"][0-9a-zA-Z]{32,}['\"]"
            ["Tokens"]="[Tt][Oo][Kk][Ee][Nn].*['\"][0-9a-zA-Z]{32,}['\"]"
            ["Passwords"]="[Pp][Aa][Ss][Ss][Ww][Oo][Rr][Dd].*['\"][^'\"]{8,}['\"]"
            ["Private Keys"]="-----BEGIN [A-Z]+ PRIVATE KEY-----"
            ["AWS Keys"]="AKIA[0-9A-Z]{16}"
            ["GitHub Tokens"]="ghp_[0-9a-zA-Z]{36}"
          )
          
          echo "### 🔐 Secrets Scan Results" >> $GITHUB_STEP_SUMMARY
          
          SECRETS_FOUND=0
          
          for pattern_name in "${!patterns[@]}"; do
            pattern="${patterns[$pattern_name]}"
            
            # Busca o padrão, excluindo arquivos específicos
            matches=$(grep -r -E "$pattern" . \
              --exclude-dir=node_modules \
              --exclude-dir=.git \
              --exclude-dir=dist \
              --exclude-dir=dist-zips \
              --exclude="*.log" \
              --exclude="*.md" \
              2>/dev/null || true)
            
            if [[ -n "$matches" ]]; then
              echo "⚠️ Potential $pattern_name found:"
              echo "$matches"
              echo "- **$pattern_name**: ⚠️ Potential matches found" >> $GITHUB_STEP_SUMMARY
              SECRETS_FOUND=$((SECRETS_FOUND + 1))
            else
              echo "- **$pattern_name**: ✅ None found" >> $GITHUB_STEP_SUMMARY
            fi
          done
          
          if [[ $SECRETS_FOUND -gt 0 ]]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "⚠️ **Warning**: Potential secrets detected. Please review the matches above." >> $GITHUB_STEP_SUMMARY
            echo "❌ Potential secrets found in code!"
            exit 1
          else
            echo "✅ No secrets detected"
          fi

  # === JOB 5: DEEP SECURITY SCAN (OPCIONAL) ===
  deep-scan:
    name: 🕵️ Deep Security Scan
    runs-on: ubuntu-latest
    if: github.event.inputs.deep_scan == 'true' || github.event_name == 'schedule'
    timeout-minutes: 20
    
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: 📦 Install Dependencies
        run: npm ci --prefer-offline --no-audit
      
      - name: 🕵️ Deep Code Analysis
        run: |
          echo "🕵️ Running deep security analysis..."
          
          # Análise de complexidade e possíveis vulnerabilidades
          echo "### 🕵️ Deep Security Analysis" >> $GITHUB_STEP_SUMMARY
          
          # Conta funções com alta complexidade
          COMPLEX_FUNCTIONS=$(grep -r "function\|=>" --include="*.js" . | wc -l || echo "0")
          echo "- **Total Functions**: $COMPLEX_FUNCTIONS" >> $GITHUB_STEP_SUMMARY
          
          # Busca por padrões suspeitos
          SUSPICIOUS_PATTERNS=0
          
          # Funções que podem ser problemáticas
          if grep -r "setTimeout.*eval\|setInterval.*eval" --include="*.js" . >/dev/null 2>&1; then
            echo "- **Suspicious Pattern**: ⚠️ setTimeout/setInterval with eval detected" >> $GITHUB_STEP_SUMMARY
            SUSPICIOUS_PATTERNS=$((SUSPICIOUS_PATTERNS + 1))
          fi
          
          # Uso de Function constructor
          if grep -r "new Function\|Function(" --include="*.js" . >/dev/null 2>&1; then
            echo "- **Suspicious Pattern**: ⚠️ Function constructor usage detected" >> $GITHUB_STEP_SUMMARY
            SUSPICIOUS_PATTERNS=$((SUSPICIOUS_PATTERNS + 1))
          fi
          
          # Acesso a propriedades dinâmicas suspeitas
          if grep -r "\[.*\+.*\]\|window\[" --include="*.js" . >/dev/null 2>&1; then
            echo "- **Suspicious Pattern**: ⚠️ Dynamic property access detected" >> $GITHUB_STEP_SUMMARY
            SUSPICIOUS_PATTERNS=$((SUSPICIOUS_PATTERNS + 1))
          fi
          
          if [[ $SUSPICIOUS_PATTERNS -eq 0 ]]; then
            echo "- **Suspicious Patterns**: ✅ None detected" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "✅ Deep security analysis completed"

  # === JOB 6: SECURITY REPORT ===
  security-report:
    name: 📊 Security Report
    runs-on: ubuntu-latest
    needs: [dependency-scan, code-analysis, manifest-security, secrets-scan]
    if: always()
    timeout-minutes: 5
    
    steps:
      - name: 📊 Generate Security Report
        run: |
          echo "# 🔒 Security Scan Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## 📋 Scan Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Trigger**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Scan Date**: $(date -u)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## 🎯 Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "- **Dependency Scan**: ${{ needs.dependency-scan.result == 'success' && '✅' || '❌' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Code Analysis**: ${{ needs.code-analysis.result == 'success' && '✅' || '❌' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Manifest Security**: ${{ needs.manifest-security.result == 'success' && '✅' || '❌' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Secrets Scan**: ${{ needs.secrets-scan.result == 'success' && '✅' || '❌' }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Status geral
          if [[ "${{ needs.dependency-scan.result }}" == "success" && "${{ needs.code-analysis.result }}" == "success" && "${{ needs.manifest-security.result }}" == "success" && "${{ needs.secrets-scan.result }}" == "success" ]]; then
            echo "## 🎉 Overall Security Status: ✅ SECURE" >> $GITHUB_STEP_SUMMARY
            echo "All security scans passed successfully!" >> $GITHUB_STEP_SUMMARY
          else
            echo "## ⚠️ Overall Security Status: ISSUES DETECTED" >> $GITHUB_STEP_SUMMARY
            echo "Some security scans detected issues. Please review the detailed results above." >> $GITHUB_STEP_SUMMARY
          fi
      
      - name: 🎯 Set Final Status
        run: |
          if [[ "${{ needs.dependency-scan.result }}" == "success" && "${{ needs.code-analysis.result }}" == "success" && "${{ needs.manifest-security.result }}" == "success" && "${{ needs.secrets-scan.result }}" == "success" ]]; then
            echo "✅ Security scan completed successfully"
            exit 0
          else
            echo "❌ Security scan detected issues"
            exit 1
          fi